version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - healprint-network

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME:-healprint}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    networks:
      - healprint-network

  chat-service:
    build: ./chat-service
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - REDIS_URL=redis://redis:6379
    networks:
      - healprint-network
    depends_on:
      - redis

  diagnostic-service:
    build: ./diagnostic-service
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
    networks:
      - healprint-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - USER_SERVICE_URL=http://user-service:8001
      - CHAT_SERVICE_URL=http://chat-service:8002
      - DIAGNOSTIC_SERVICE_URL=http://diagnostic-service:8003
    depends_on:
      - user-service
      - chat-service
      - diagnostic-service
    networks:
      - healprint-network

  # Frontend service (optional - for development)
  frontend:
    build: ../healprint-client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8002
    depends_on:
      - chat-service
    networks:
      - healprint-network


networks:
  healprint-network:
    driver: bridge
